<?php

namespace My\DataSourceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApplyJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplyJobRepository extends EntityRepository
{
}
