# src/My/DataSourceBundle/Resources/config/doctrine/Feed.orm.yml
My\DataSourceBundle\Entity\Feed:
  repositoryClass: My\DataSourceBundle\Repository\FeedRepository
  type: entity
  table: feed
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    pusher_id:
      type: integer
      nullable: true
    receiver_id:
      type: integer
      nullable: true
    content_json:
      type: text
      nullable: true
      options:
        comment: format content for feed
    status:
      type: integer
      nullable: true
      options:
        default: 1
        comment: 1-unread, 2-read
    created_at:
      type: datetime
      nullable: true
    updated_at:
      type: datetime
      nullable: true
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue ]